name: Prover e2e test

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop", "release_*", "durian" ]
  pull_request:
    branches: [ "main", "develop", "release_*", "durian" ]

jobs:
  e2e-collection-tests:

    runs-on: [self-hosted, linux, X64, hc, hm]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install snarkjs
      run: npm list -g snarkjs || npm -g install snarkjs
    - name: make
      run: cd src/grpc && make && cd ../.. && make generate && make -j
    - name: remove all config 
      run: rm -rf config
    - name: remove old proofs
      run: rm -rf runtime/output/*
    - name: list gha config files
      run: ls /home/gha/v9.0.0-rc.1-fork.13/config/
    - name: link files
      run: ln -s /home/gha/v9.0.0-rc.1-fork.13/config/ config
    - name: list local config files
      run: ls config
    - name: run collection native tests
      run: ./build/zkProver -c testvectors/config_collection_native.json
    - name: run collection generated tests
      run: ./build/zkProver -c testvectors/config_collection_generated.json
    - name: run e2e tests
      run: ./build/zkProver -c testvectors/config_runFile_e2e.json 
    - name: run snarkjs verification
      run: snarkjs ffv config/final/final.fflonk.verkey.json $(ls -t runtime/output/*.gen_final_proof_public.json | head -n1) $(ls -t runtime/output/*.final_proof.proof.json | head -n1)
    - name: clean
      run: make clean