name: Prover e2e test

on:
  workflow_dispatch:
  push:
    branches: [ "main","develop", "release_*" ]
  pull_request:
    branches: [ "main","develop", "release_*" ]

jobs:
  build:

    runs-on: [self-hosted, linux, X64, hc, hm]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install snarkjs
      run: npm -g install snarkjs
    - name: make
      run: cd src/grpc && make && cd ../.. && make -j
    - name: remove all config 
      run: rm -rf config
    - name: remove old proofs
      run: rm -rf runtime/output/*
    - name: link files
      run: ln -s /root/v3.0.0-RC3-fork.6/config/ config
    - name: run e2e tests
      run: ./build/zkProver -c testvectors/config_runFile_e2e.json 
    - name: run snarkjs verification
      run: snarkjs ffv config/final/final.fflonk.verkey.json $(ls -t runtime/output/*.gen_final_proof_public.json | head -n1) $(ls -t runtime/output/*.final_proof.proof.json | head -n1)