name: Build docker image tagged

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # this action will only run on tags that follow semver

jobs:
  build-docker:
    runs-on: [self-hosted, linux, X64, hc]

    outputs:
      sha_short: ${{ steps.setvars.outputs.sha_short }}
      tag: ${{ steps.setvars.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Executor 13 AVX512
        id: docker_build_executor_13_avx512
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: executor
          tags: |
            hermeznetwork/zkevm-prover:${{ github.ref_name }}-fork.13.avx512
          build-args: |
            ARG_PROVER_FORK_ID=13
            avx512=1

      - name: Build and push Executor 13
        id: docker_build_executor_13
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: executor
          tags: |
            hermeznetwork/zkevm-prover:${{ github.ref_name }}-fork.13
          build-args: |
            ARG_PROVER_FORK_ID=13
            avx512=0
            
