name: Build docker image and run node tests

on:
  push:
    branches: [ develop, main ]

jobs:
  build-docker:
    runs-on: [self-hosted, linux, X64, hc]

    outputs:
      image_tag: ${{ steps.setvars.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        id: setvars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=image_tag::latest"
            echo "::set-output name=dbg::0"
          else
            echo "::set-output name=image_tag::develop"
            echo "::set-output name=dbg::1"
          fi

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            dbg=${{ steps.setvars.outputs.dbg }}
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hermeznetwork/zkevm-prover:${{ steps.setvars.outputs.sha_short }}
            hermeznetwork/zkevm-prover:${{ steps.setvars.outputs.image_tag }}

  node-tests:
    needs: build-docker
    uses: 0xPolygonHermez/zkevm-node/.github/workflows/test-from-prover.yml@develop
    with:
      prover_image: hermeznetwork/zkevm-prover:${{needs.build-docker.outputs.image_tag}}"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
